updating code approval job

diff --git a/.github/workflows/ci-code-approval.yml b/.github/workflows/ci-code-approval.yml
--- a/.github/workflows/ci-code-approval.yml
+++ b/.github/workflows/ci-code-approval.yml
@@ -38,13 +38,8 @@ jobs:
           go-version-file: 'go.mod'
           cache-dependency-path: "**/*.sum"
 
-      - name: "Configure git for private modules"
-        env:
-          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: git config --global url."https://x:${GITHUB_API_TOKEN}@github.com".insteadOf "https://github.com"
-
       - name: golangci-lint
-        uses: golangci/golangci-lint-action@v7
+        uses: golangci/golangci-lint-action@v8
         with:
           version: latest
           args: --verbose --timeout 5m
@@ -69,7 +64,7 @@ jobs:
           path: |
             ~/.cache/bazel
 
-      - name: Run Mage
+      - name: Build and Test
         uses: magefile/mage-action@v3
         with:
           version: latest
@@ -82,32 +77,6 @@ jobs:
           key: bazel
           path: |
             ~/.cache/bazel
-
-  code-generation:
-    name: "Code Generation"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: 'go.mod'
-          cache-dependency-path: "**/*.sum"
-
-      - name: Restore bazel cache
-        uses: actions/cache/restore@v4
-        with:
-          key: bazel
-          path: |
-            ~/.cache/bazel
-
-      - name: Run Mage
-        uses: magefile/mage-action@v3
-        with:
-          version: latest
-          args: generate:diff
 
   diff:
     name: "Diff"
@@ -134,6 +103,42 @@ jobs:
         with:
           version: latest
           args: fixit
+
+      - name: Check Diff
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "[ERROR] Changes detected:"
+            git status --porcelain
+
+            echo "Make sure to run 'mage fixit' before committing."
+            exit 1
+          fi
+
+  codegen:
+    name: "Code Generation"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version-file: 'go.mod'
+          cache-dependency-path: "**/*.sum"
+
+      - name: Restore bazel cache
+        uses: actions/cache/restore@v4
+        with:
+          key: bazel
+          path: |
+            ~/.cache/bazel
+
+      - name: Run Mage
+        uses: magefile/mage-action@v3
+        with:
+          version: latest
+          args: generate
 
       - name: Check Diff
         run: |
